### ISSUE TITLE
Test on F746 DISCO board

### ISSUE THREAD

**Issue by szjdb** [chillmf/STM32F769-FT8-Transceiver#2]
Hi, Charles,
Thanks for your effort on porting the FT8 lib on F769 DISCO broad. Great!
I am also trying to port the FT8 lib on my F747 board ,but have some issues.
1. Should I record all the 15s long wave data and then process it by the lib? It will cost at least 360KB memory for the wave data.  Or can I break it into each 3840 block and process them in realtime. 
2. Can I modify the sampling rate from 12KHz to 6KHz  to reduce the bandwidth ?

Best Regards & 73!
James

**Comment by kgoba** [comment]
Hi James, I'm the author of the ft8 decoder library. I created an application for the 746g discovery board a while ago, if you'd like I can share the code with you. Unfortunately not much is documented, but I can walk you through it if you'd like. All I remember now is that I configured the audio codec to record samples at 8 kHz rate, and then used DSP resampling to get it to 6.4 kHz which also works very well with the integer division ratios for ft8 decoding.

**Comment by szjdb** [comment]
Hi, Karlis,

Many Thanks indeed ! 

I am working on the project for these day and hope to decode/encode the FT8 in the STM32F747.  I am wondering how to process the wave data block by block.

Your sample code will be great help!

Many thanks for your great work which make it possible!




Best Regards & 73

James  












DB.JIANG


***@***.***


13603052469







电子名片新出VIP模板啦，快来体验>>




扫一扫,


快速添加名片到手机




--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: "Kārlis Goba" ***@***.***>
 

 
 发送时间: 2021-08-05 17:41:48
 

 
 收件人:chillmf/STM32F769-FT8-Transceiver ***@***.***> 

 
 抄送:jdb-139 ***@***.***>,Author ***@***.***> 

 
 主题: Re: [chillmf/STM32F769-FT8-Transceiver] Test on F746 DISCO board (#2)
 





 Hi James, I'm the author of the ft8 decoder library. I created an application for the 746g discovery board a while ago, if you'd like I can share the code with you. Unfortunately not much is documented, but I can walk you through it if you'd like. All I remember now is that I configured the audio codec to record samples at 8 kHz rate, and then used DSP resampling to get it to 6.4 kHz which also works very well with the integer division ratios for ft8 decoding.

 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
